destination: "dst"

clean: true

metadata: true

rules:
  - from: "src"
    targets:
      - "log_folder"
      - "*log.txt"
    to: "log"
    on-start:
      - name: "Show Rule 1 welcome message"
        command: ["echo", "This is the first rule!"]
        output: true
        timeout: 3
    on-end:
      - name: "Show Rule 1 goodbye message"
        command: ["echo", "Bye Rule 1!"]
        output: true
        timeout: 5

  - from: "src"
    targets:
      - "config_file.txt"
      - "config_link.txt"
    to: "config"

hooks:
  pre-backup:
    - name: "Show welcome message"
      command: ["echo", "Welcome to cockup!"]
      output: true
      timeout: 3
    - name: "Show environment variables"
      command: ["env"]
      output: true
      timeout: 3
      env:
        USER: "cockup_user"
        CUSTOM_VAR: "custom_value"

  post-backup:
    - name: "Show goodbye message"
      command: ["echo", "See you next time!"]
      output: true
      timeout: 5
