name: Build and Release to PyPI

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - uses: astral-sh/setup-uv@v6

      # install dependencies and build
      - name: Install dependencies and build
        run: |
          python -m pip install --upgrade pip
          uv pip install -e .
          uv build

      # upload artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pypi-dist
          path: dist/
          retention-days: 1

  test:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/p/cockup
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: Gather all artifacts
        uses: actions/download-artifact@v4
        with:
          name: pypi-dist
          path: dist/

      - name: Publish distribution to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

  release:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cockup
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing

    steps:
      - name: Gather all artifacts
        uses: actions/download-artifact@v4
        with:
          name: pypi-dist
          path: dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Release all artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
